title: YouYehao's Homepage
page-top-title: YouYehao
top-section-bg-text: Record Learning of everything
home-subtitle: YouYehao;|&ensp;游烨昊
copyright-text: '&copy; YouYehao 2023-2025. All Rights Reserved.'
